# This rule is not used by the project volume-branch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to volumes.arbit-tech.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-branch-operator
    app.kubernetes.io/managed-by: kustomize
  name: branchpool-viewer-role
rules:
- apiGroups:
  - volumes.arbit-tech.com
  resources:
  - branchpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - volumes.arbit-tech.com
  resources:
  - branchpools/status
  verbs:
  - get
