# This rule is not used by the project volume-branch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over volumes.arbit-tech.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-branch-operator
    app.kubernetes.io/managed-by: kustomize
  name: branchsource-admin-role
rules:
- apiGroups:
  - volumes.arbit-tech.com
  resources:
  - branchsources
  verbs:
  - '*'
- apiGroups:
  - volumes.arbit-tech.com
  resources:
  - branchsources/status
  verbs:
  - get
