apiVersion: volumes.arbit-tech.com/v1alpha1
kind: BranchSource
metadata:
  labels:
    app.kubernetes.io/name: volume-branch-operator
    app.kubernetes.io/managed-by: kustomize
  name: branchsource-sample
spec:
  # TODO(user): Add fields here
